server:
  port: 9090
database:
  url: root:password@tcp(127.0.0.1:3306)/qa?charset=utf8mb4&parseTime=True&loc=Local
jwt:
  secretKey: your-jwt-secret-key-here
cos:
  secretId: your-tencent-cloud-secret-id
  secretKey: your-tencent-cloud-secret-key
